huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|          | 0/6093 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/vast/palmer/home.mccleary/xc392/Oncology-based-IE-on-HP/models/medical_ner_train.py", line 202, in <module>
    trainer.train()
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/transformers/trainer.py", line 2508, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches, args.device)
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/transformers/trainer.py", line 5224, in get_batch_samples
    batch_samples += [next(epoch_iterator)]
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/accelerate/data_loader.py", line 566, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 764, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xc392/.conda/envs/clinical-ner/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/vast/palmer/home.mccleary/xc392/Oncology-based-IE-on-HP/models/medical_ner_train.py", line 106, in __getitem__
    encoded_labels[idx] = labels[i]
IndexError: list index out of range
  0%|          | 0/6093 [00:00<?, ?it/s]
